# Generated by Django 4.1.7 on 2023-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=128)),
                ("manufacturer", models.CharField(max_length=128)),
                ("Vehicle", models.CharField(max_length=12)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
