# Generated by Django 4.1.7 on 2023-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=128)),
                ("manufacturer", models.CharField(max_length=128)),
                ("vehicle", models.CharField(max_length=12)),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
